version: '3.8'

services:
  agendamento-app:
    build: .
    container_name: agendamento-sistema
    ports:
      - "6000:6000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - REDIS_HOST=redis
      - TZ=America/Sao_Paulo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./backups:/app/backups
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - agendamento-network
      - npm-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: agendamento-redis
    ports:
      - "6379:6379"
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - agendamento-network
    restart: unless-stopped

networks:
  agendamento-network:
    driver: bridge

  npm-network:
    external: true
    name: npm-nginx_default
